name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version required for your project

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the React App
      - name: Build the App
        run: npm run build

      # Step 5: Copy Build Files to Root
      - name: Move Build Files
        run: |
          rm -rf ./* # Remove everything in the root
          mv build/client/* . # Move the build files to the root
          touch .nojekyll # Prevent GitHub Pages from ignoring files starting with underscores

      # Step 6: Commit and Push Changes
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push origin main --force
